### ISSUE TITLE
Use letter notation in mainline

### ISSUE THREAD

**Issue by rfetick** [lehoff/skak#2]
Hello,

First of all, thanks a lot for your work!
I was just wondering if it is possible to use the letter notation (e.g. `Ke2`) instead of the pieces symbols when printing the `\mainline`. I couldn't see this in the documentation. Sorry if this information effectively appears in the doc and I missed it.

Kind regards,

Romain

**Comment by lehoff** [comment]
I have not touched this in the longest time, but I think you have to dabble with `chessfss` to change the output to text.

```
\settextfiglanguage
```
This should switch to text output.

You can also change the letters for a language:
```
\settextfigchars{english}{K}{Q}{R}{B}{N}{P}
```
The docs for `chessfss` is your friend for this. 
https://ctan.org/pkg/chessfss?lang=en

Let me know what the magic command is.

**Comment by rfetick** [comment]
Hello,

Thanks for the document! The command `\usetextfig` does the job :) And then setting the language allows to define the letters accordingly to your country conventions.

Kind regards,

Romain

**Comment by lehoff** [comment]
Do you have an example that we can add to the docs?

**Comment by rfetick** [comment]
Below is the minimal example that reproduces the solution, adapted to french notation in order to also show that the language selection works.

```latex
\documentclass[12pt]{article}

\usepackage{skak}

\usetextfig
\newskaklanguage{french}{RDTFCP}
\skaklanguage[french]
\settextfiglanguage{french}

\begin{document}

\newgame
\mainline{1.Cf3}

\end{document}
```
